# Generated by Django 6.1.1 on 2026-09-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
