# Generated by Django 6.1.1 on 2026-09-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_phone_number_patient_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
    ]
